### ISSUE TITLE
Data Partition contingency/detection

### ISSUE THREAD

**Issue by elevatorguy** [queso-fuego/uefi-dev#12]
Perhaps if `$(KERNEL)` and any other needed file(s) become loadable via ESP, this is supported?

If not ideal design-wise; what about detection - if file(s) aren't found?

Pulled your latest changes regarding `INSTALL.DAT`; applied to USB - may remove Text Mode. I was guessing `FILE.EFI` is the way forward as my laptop has a way to boot from file with the built-in BIOS menu, but if flashed; `file.img` is still a valid option. Hadn't considered `INSTALL.DAT` non-ESP placement, although ESP may be more convenient for uninstalling.

ESP: the `DISK_LBA`, `DISK_SIZE`, and `FILE_SIZE` note(s) aren't needed (if using `EFI_FILE_INFO`) and `INSTALL.DAT` doesn't necessarily signify the presence of a Data Partition. Presently tempted to make a pull-request to combine `DATAFLS.INF` and `DSKIMG.INF`; almost forgot about the one open - may force-push to combine commits for easier merging if not solved already and can't wait to see a multi-threaded future of OS-less development. Thanks so much for pushing the field forward by opening up, youtube or otherwise.

Author's note: have since found [reference](https://uefi.org/specs/PI/1.9/V2_DXE_Boot_Services_Protocols.html) as `EFI_MP_SERVICES_PROTOCOL` presently not implemented.

**Comment by elevatorguy** [comment]
The Issue:
```
Header bytes: [0] [0] [41] [8B]
File Format: No format found, assuming flat binary file

Original Kernel address: 8E18D000, size: 50128, entry point: 8E18D000
Higher Address entry point: 80000000

Press any key to load kernel...
```
Kernel isn't loaded from file present with FILE.EFI. Loading from an array instead of a file at runtime is possible, although that may slow project compilation. Either way, a graceful exit or shutdown would be preferred.

For reference - if flashed:
```
Header bytes: [7F] [45] [4C] [46]
File Format: ELF
Type: 3, Machine: 3E, Entry Point: 0x8000
Pgm headers offset: 64, Elf Header Size: 64
Pgm entry size: 56, # of Pgm headers: 10

Loadable Program Headers:
2: Offset: 0, Vaddr: 0, Paddr: 0, FileSize: 3E0
    MemSize: 3E0, Alignment: 1000
3: Offset: 1000, Vaddr: 1000, Paddr: 1000, FileSize: 7291
    MemSize: 7291, Alignment: 1000
4: Offset: 9000, Vaddr: 9000, Paddr: 9000, FileSize: 1980
    MemSize: 1980, Alignment: 1000
5: Offset: AF00, Vaddr: BF00, Paddr: BF00, FileSize: 2B0
    MemSize: 328, Alignment: 1000

Memory needed for file: 0xD000 bytes

Original Kernel address: 8B369000, size: 53248, entry point: 8B371000
Higher Address entry point: 80008000

Press any key to load kernel...
```

**Comment by queso-fuego** [comment]
Added ESC as a back out option here https://github.com/queso-fuego/uefi-dev/commit/4c6906adec655ab268e48d6137c36b4e9850bdb7

But that doesn't help if you want to go to the loaded program without input. I'm not sure there is a way to detect issues when trying to run the loaded program, to be able to return.

I don't really know what you mean by EFI_FILE_INFO and FILE.EFI, but if you want the kernel or other programs to only be in the ESP that would be fine and work simpler. You would be limited to the ESP size, at least to start with, but that may not be an issue if you are fine with the local ESP & FAT filesystem or don't need anything larger than your ESP, or maybe your ESP is the size of the disk anyway. 

Using a data/other partition you don't have a way of knowing in general where a file is, or what format it is really. You can know where on disk it is by referencing the lba and the size of it by the file size, but only if you know before hand, such as using a tool like I did to put the file there. You would have to make something else to be to find your files if they're outside the ESP.
Not sure how you would get the info otherwise from a non-formatted partition without a filesystem on it. 

You could have a better tool that puts in a FAT or other filesystem and use that instead and not need the file info setup, of course.

**Comment by elevatorguy** [comment]
Attached FILE.TXT.
FILE_NAME=kernel.elf
FILE_SIZE=50272
DISK_LBA=71680
FILE_NAME=ter-132n.psf
FILE_SIZE=17151
DISK_LBA=71779
DISK_SIZE=37785600

**Comment by elevatorguy** [comment]
![file](https://github.com/user-attachments/assets/b672a04d-43d7-45f1-947e-da34e80c6178)

The header bytes are different than above when flashing a binelf, but you may be right that there isn't a guarantee - not necessarily - of detection in the case the bytes are uninitialized.

**Comment by elevatorguy** [comment]
FILE.EFI in ESP:

Header bytes: [0] [0] [41] [8B]
File Format: No format found, assuming flat binary file

Original Kernel address: 8E191000, size: 35147, entry point: 8E191000
Higher address entry point: 80000000

Press ESC to abort, or another key to load kernel...

**Comment by elevatorguy** [comment]
Confirmed reliance on the first two header bytes alone lacks coverage.

Regardless of the kernel code and ESP support - [5610272](https://github.com/queso-fuego/uefi-dev/commit/5610272c16a024ce86cbdbad6d538775702b0d1a) - if a menu item, instead.

**Comment by queso-fuego** [comment]
What addresses are you flashing to?
Can you put "llx" for the print line for entry point and higher address entry point, to see a full 64 bit address?

I haven't seen the original buffer put at a higher address than the ending kernel addresses at 0xFFFFFFFF80000000, want to rule that out.
But either way, 35147 bytes is 8.58 4KiB pages, or 9 pages when mapped, 80000000 + 9000 = 80009000 so shouldn't overlap.

Actually, if it's a flat binary it's only using the first allocated buffer anyway, the entry point being the start of the buffer, if the bytes match the binary there I'm not sure why it wouldn't work.

I'll try to find other places to troubleshoot.

Can you verify the starting header bytes in the binary match the bytes that are returned when loading the kernel? e.g.
```
$ xxd -l 32 kernel.binelf 
00000000: 5548 89e5 5657 4881 ec20 0100 0044 0f29  UH..VWH.. ...D.)
00000010: 7de0 440f 2975 d044 0f29 6dc0 440f 2965  }.D.)u.D.)m.D.)e
```

I get header bytes [55][48][89][E5] which matches the starting bytes.

I get that that's what your saying, that it doesn't match and isn't correctly loading the file, but that could narrow things down to the disk lba loading code.

**Comment by queso-fuego** [comment]
Also, you could maybe paste or mail me your kernel that's failing, source or binary, and I can try loading it on my hardware.

**Comment by elevatorguy** [comment]
> 13.6.3 Tape Header Format
The boot tape will contain a Boot Tape Header to indicate it is a valid voot tape. The Boot Tape Header must be located within the first 20 blocks on the tape. One or more tape filemarks may appear prior to the Boot Tape Header so that boot tapes may include tape label files. The Boot Tape Header must begin on a block boundary and be contained completely within a block. The Boot Tape Header will have the following format:

> Table 13.24: Tape Header Formats

Seems relevant and a CRC may solve this issue if the root cause is corruption, right?

We already have `bs->CalculateCrc32`:

> NOTE: Unless otherwise specified, UEFI uses a standard CCITT32 CRC algorithm with a seed polynomial value of 0x04c11db7 for its CRC calculations.

Why not use it?

> 7.5.7 EFI_BOOT_SERVICES.CalculateCrc32()

**Comment by queso-fuego** [comment]
Not using tape drives, I doubt you are either, but that would be really interesting to see if so.
Could be something with the Block IO media IoAlign or BlockSize values, but I'd think a 0x1000 aligned buffer would be fine to read into.

**Comment by elevatorguy** [comment]
Seemingly unrelated error, though noticed this does happen after the first time: https://github.com/queso-fuego/uefi-dev/blob/052c6856fc2a5b14ff7d343abf1851809eace71d/efi_c/efi_lib.h#L2166 Using something ESP-only based on [what was] `branch2` [likely of 5610272], both fonts are printed to screen if continuing as menu item. As for what happens via kernel with local ESP-only change(s):

![file](https://github.com/user-attachments/assets/d4866a12-fbae-4ab3-846c-238729f53536)
Continuing; nothing printed - may add EFI_CRC to FILE.TXT.

For `file.img`, in placing `$(KERNEL)` - to both data and ESP - with `write_gpt`. If possible, I can try to see if what happens is similar; not sure if the kernel will load if using `file.img` like that. If it does; not sure what that tells us about the difference between the two use cases, presently. The text does print if the kernel file isn't in ESP, but elsewhere in `file.img`. For some reason - via the kernel - it only prints the second font if having tried the menu item first, but skipping that - it does still print both fonts.
![file](https://github.com/user-attachments/assets/cad32724-4627-4363-9bb4-72428f3179e5)

**Comment by queso-fuego** [comment]
If you're loading the kernel from ESP with read_esp_file_to_buffer(), you may have to use EfiLoaderCode for the memory type for bs->AllocatePool(), it's set to EfiLoaderData right now, which may not have execution permissions.

That's partly why I had to add the extra parameter to read_disk_lbas_to_buffer to get EfiLoaderCode vs. data memory. Maybe could add that for read_esp_file_to_buffer() also.

**Comment by elevatorguy** [comment]
https://github.com/queso-fuego/uefi-dev/blob/763ba02fc3974a1ae8f3883795a124248223b16a/efi_c/efi.c#L1361
Since `read_data_partition_file_to_buffer` does actually fail gracefully if `DATAFLS.INF` isn't found; my mistake was having the makefile [copy that over](https://github.com/elevatorguy/file/commit/59926525cb2758855f23147c1b3ca500b2cfac3b#diff-beda42571c095172ab63437d050612a571d0d9ddd3ad4f2aecbce907a9b7e3d0R103) - even though ESP-only. Thanks for troubleshooting anyway even though I didn't recognize the filesize prerequisite for kernel loading. Not sure how, as FILE.TXT was attached; but yea, glad I caught it in the commit review, however late.

**Comment by elevatorguy** [comment]
Not that the mistake somehow invalidates ESP loading as a contingency, though can confirm `EfiLoaderCode` didn't execute, or at least didn't seem to appear to, as I tried that before closing. Made [#4](https://github.com/queso-fuego/UEFI-GPT-image-creator/pull/4) and [#5](https://github.com/queso-fuego/UEFI-GPT-image-creator/pull/5) for FILE.TXT, but would need to change here too - #14.

**Comment by elevatorguy** [comment]
Is chapter twenty-two worth the read?

**Comment by queso-fuego** [comment]
If you want to write programs or modules for the EFI Byte Code VM, for drivers, sure. If you have need for custom drivers that could run on multiple architectures. 
That's for drivers specifically and not loading and running normal EFI applications like an OS loader though, and I'm not sure how widespread support is for the byte code.
