### ISSUE TITLE
Cannot use gnu-efi or idk how to.

### ISSUE THREAD

**Issue by CHatingPython** [queso-fuego/uefi-dev#2]
I am trying to use gnu-efi but it always fails...

Could you tell me is it "feature" or how could I do that?

**Comment by queso-fuego** [comment]
It's not really a feature, but this repo will be all homemade/"from scratch" code, and won't be using any 3rd party libraries like gnu-efi.
Sort of like a lesser alternative or subset of it at most.

That said, without any more info I'm not sure where or how gnu-efi is failing for you or how to fix it. Even if I don't plan to support gnu-efi, posix-efi, or others, a repro case would be good in the future for a sanity check, if nothing else.
