### ISSUE TITLE
In function ‘add_file_to_esp’: ignoring return value of ‘fread’ declared with attribute ‘warn_unused_result’

### ISSUE THREAD

**Issue by abolfazlsamini** [queso-fuego/uefi-dev#5]
I did the steps described in [here](https://github.com/queso-fuego/uefi-dev?tab=readme-ov-file#building)
but as in the title says when I run **make** in "UEFI-GPT-image-creator" I get this message
![image](https://github.com/queso-fuego/uefi-dev/assets/53626987/0ffced63-5174-4129-bae2-ff64cd6cf9bd)
and when I run **make** in "efi_c" this is what I get
![image](https://github.com/queso-fuego/uefi-dev/assets/53626987/ec73ab24-a116-499f-adac-de735b908bae)
I'm new to this, so I'm not sure what I'm doing wrong
I have:
Ubuntu 22.04.4 LTS
GNU Make 4.3
gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Ubuntu clang version 14.0.0-1ubuntu1.1

**Comment by helix-osdev** [comment]
This would be a bad work around to suppress the warning... But you could do so by adding `-Wno-unused-result`

**Comment by queso-fuego** [comment]
This should be fixed now with this commit: 85f254359dd78d77ec751366fbb022aeca7bdb55

https://github.com/queso-fuego/uefi-dev/commit/85f254359dd78d77ec751366fbb022aeca7bdb55

All fread() uses should have their return values used now in conditionals, hopefully that clears up the warnings. Although I don't get them with -Wunused-result on my setup, gcc must have different warnings on different systems, and versions.
