### ISSUE TITLE
Simple Pointer Protocol - Automatic Boot

### ISSUE THREAD

**Issue by elevatorguy** [queso-fuego/uefi-dev#8]
If Boot Order in BIOS is set to device with `EFI/BOOT/BOOTX64.EFI` first, we get:
"ERROR: Could not find any valid SPP Mode."

However, regardless of Boot Order setting; booting via selection:
S.P.P. found.

Issue initially found without A.P.P. enabled; vendor has BIOS "Touch Device" toggle - issue remains.

**Comment by queso-fuego** [comment]
That sounds like it doesn't get initialized or enabled unless manually selecting the boot entry, which is interesting.
I'll test on my hardware, but can try enabling all devices found by calling BootServices->ConnectController() on all handles, using the example on page 181 of the uefi spec. That should enable drivers if they aren't enabled yet, to rule that out.

I'll probably add code for that at startup anyway, it shouldn't harm anything.

**Comment by queso-fuego** [comment]
Should be fixed by adding ConnectController() code in commit afc290c030c322a224b06d152f5abad646a279a8
